### ISSUE TITLE
Contains Filter Dropdown not working

### ISSUE THREAD

**Issue by ctassparker** [uptick/react-object-list#16]
In the demo on storybook, I can't select the Does Not Contain in the filter.

**Comment by ctassparker** [comment]
![screenshot from 2018-03-27 13-28-03](https://user-images.githubusercontent.com/14171349/37943302-c04a6d22-31c2-11e8-881e-30a569aa7c90.png)

**Comment by Sticky-Bits** [comment]
Filter label is also not showing ._.

**Comment by Sticky-Bits** [comment]
All will be fixed by https://github.com/uptick/react-object-list/pull/20/files

**Comment by ctassparker** [comment]
thanks @Sticky-Bits
